tap "adoptopenjdk/openjdk"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"

cask_args appdir: "/Applications"

brew "ack"
brew "binutils"
brew "python"
brew "ccat"
brew "cocoapods"
brew "coreutils"
brew "diffutils"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gawk"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-which"
brew "gnupg"
brew "grep"
brew "gzip"
brew "jq"
brew "jupyterlab"
brew "mas"
brew "moreutils"
brew "neovim"
brew "node"
brew "pyenv"
brew "rbenv"
brew "rename"
brew "rsync"
brew "ruby"
brew "screen"
brew "starship"
brew "stow"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "zplug"
brew "zsh"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

cask "1password"
cask "adoptopenjdk8"
cask "adoptopenjdk8-jre"
cask "airpass"
cask "alacritty"
cask "alfred"
cask "bitbar"
cask "dozer"
cask "expo-xde"
cask "firefox"
cask "flux"
cask "font-hack"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "intel-haxm"
cask "intellij-idea-ce"
cask "kap"
cask "lulu"
cask "miniconda"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "transmission"
cask "visual-studio-code"

# install gradle here, since by now the jdk is installed
brew "gradle"

mas "1Password", id: 1333542190
mas "Gifski", id: 1351639930
mas "Pikka", id: 1195076754
mas "Spark", id: 1176895641
